### ISSUE TITLE
Identifying which crossfilter triggered an update

### ISSUE THREAD

**Issue by javiercejudo** [Wildhoney/ngCrossfilter#18]
I was listening for updates in a crossfilter using the `crossfilter/updated` event, but I couldn't find a clean way to identify from which crossfilter the event originated when there's more than one.

Maybe I'm missing something, but I guess a backwards-compatible approach would be to optionally set a name/id for a crossfilter and pass that name along with the broadcasted event. It could look something like this:

```js
$scope.ngc = new Crossfilter(response.data, 'id', 'persistent');
$scope.ngc.setCrossfilterName('myCrossfilter1');

$scope.$on('crossfilter/updated', function(event, collection, crossfilterName) {
  if ('myCrossfilter1' === crossfilterName) {
    // ...
  }
};
```

Thoughts? I'm happy to submit a PR if you think it's worth it!

**Comment by Wildhoney** [comment]
This would he useful, Javier! Maybe call the function `crossfilter.identifyAs` instead, but that's just personal preference.

**Comment by javiercejudo** [comment]
Sounds good, I like `identifyAs`. Thanks for the quick reply! I'll submit a PR soon-ish.
