### ISSUE TITLE
Advantage over using crossfilter directly?

### ISSUE THREAD

**Issue by manikantag** [Wildhoney/ngCrossfilter#23]
Hi, I like the idea, but I m not getting the clear benefits of using ngCrossfilter over crossfilter directly in the controller, like I use Lodash. Can you please clarify? Thanks.

**Comment by Wildhoney** [comment]
`ngCrossfilter` is merely a wrapper around `crossfilter`. It adds many utilities that you wouldn't get with `crossfilter` by default &ndash; such as persisent and transient filtering. `ngCrossfilter` also adds a handful of convenience methods that can be invoked directly from your ng template. Another thing that `ngCrossfilter` adds is a simplified way of updating models currently in the `crossfilter` collection.

If you don't need any of the functions you see in the `README` though, then I suggest using `crossfilter` directly is the way forward for you :+1:

**Comment by manikantag** [comment]
I see. I'll share my experience. Thanks.
